export {
  PRIZES,
  VISUAL_SEGMENTS,
  STORAGE_KEY_FIRST_SPIN,
  STORAGE_KEY_SECOND_SPIN,
  STORAGE_KEY_CUSTOMER,
  STORAGE_KEY_FINAL,
  SPIN_DURATION_MS,
  EXTRA_SPINS,
  GOLD,
  GOLD_DARK,
  GOLD_LIGHT,
} from "./prizes";
